name: Run tests

on:
  push

jobs:
  phpunit:
    name: Run PHPUnit
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - uses: php-actions/composer@v6
      - uses: php-actions/phpunit@v3
