name: Run tests

on:
  push

jobs:
  tests:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        php: [ 8.2, 8.1, 8.0, 7.4 ]
        laravel: [ 10, 9, 8 ]
        dependency-version: [ prefer-stable ]
        os: [ ubuntu-22.04 ]
        include:
          - laravel: 10
            testbench: 8.*
          - laravel: 9
            testbench: 7.*
          - laravel: 8
            testbench: 6.*
        exclude:
          - laravel: 10
            php: 8.0
          - laravel: 10
            php: 7.4
          - laravel: 9
            php: 7.4

    name: PHP${{ matrix.php }} - Laravel ${{ matrix.laravel }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: curl, libxml, mbstring, zip
          coverage: none

      - name: Install dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}.*" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
          composer update --${{ matrix.dependency-version }} --no-interaction

      - name: Execute tests
        run: vendor/bin/phpunit --testdox --configuration phpunit.xml
